"""Metadata for one encrypted blob on disk."""
from __future__ import annotations

from datetime import datetime, timezone

from sqlalchemy import BigInteger, String, Text
from sqlalchemy.orm import Mapped, mapped_column, relationship

from app.extensions import db
from app.models.types import UtcDateTime


def utcnow() -> datetime:
    return datetime.now(timezone.utc)


class StoredFile(db.Model):
    """A single uploaded file.

    ``original_filename`` is *metadata only* and is never used to build a
    filesystem path; the bytes live at ``stored_filename``, a random name
    generated by the storage backend.
    """

    __tablename__ = "files"

    id: Mapped[int] = mapped_column(primary_key=True)

    # Display name, as supplied by the uploader. Sanitised, never trusted.
    original_filename: Mapped[str] = mapped_column(String(255), nullable=False)
    # Random opaque name on disk, e.g. "3f9a...c1.enc".
    stored_filename: Mapped[str] = mapped_column(String(128), nullable=False, unique=True, index=True)
    # Backend identifier, so a future S3 backend can coexist with local files.
    storage_backend: Mapped[str] = mapped_column(String(32), nullable=False, default="local")

    mime_type: Mapped[str] = mapped_column(String(128), nullable=False, default="application/octet-stream")
    # Plaintext size in bytes (the blob on disk is slightly larger).
    size: Mapped[int] = mapped_column(BigInteger, nullable=False, default=0)

    # Per-file data key, itself encrypted with the server master key.
    encrypted_file_key: Mapped[str] = mapped_column(Text, nullable=False)

    uploaded_at: Mapped[datetime] = mapped_column(UtcDateTime, default=utcnow, nullable=False)

    shares: Mapped[list["Share"]] = relationship(  # noqa: F821
        back_populates="file", cascade="all, delete-orphan", passive_deletes=True
    )

    def __repr__(self) -> str:  # pragma: no cover - debugging aid
        return f"<StoredFile id={self.id} size={self.size}>"
